# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini._mlir_pkg.arith
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini._mlir_pkg.arith
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class AddFOp(Object):
    lhs: Any
    rhs: Any


class AddIOp(Object):
    lhs: Any
    rhs: Any


class CmpIOp(Object):
    lhs: Any
    rhs: Any


class ConstantOp(Object):
    args: List[Any]


class FloatType(Object):
    name: str


class IntegerType(Object):
    name: str


class MulFOp(Object):
    lhs: Any
    rhs: Any


class MulIOp(Object):
    lhs: Any
    rhs: Any


class SubFOp(Object):
    lhs: Any
    rhs: Any


class SubIOp(Object):
    lhs: Any
    rhs: Any


class __ffi_prim_ty__(Object):
    name: str



# ===== Factories / hooks =====

def addf(a: Any, b: Any) -> AddFOp: ...
def addi(a: Any, b: Any) -> AddIOp: ...
def cmpi(a: Any, b: Any) -> CmpIOp: ...
def constant(value: Any, ty: Any) -> ConstantOp: ...
def mulf(a: Any, b: Any) -> MulFOp: ...
def muli(a: Any, b: Any) -> MulIOp: ...
def subf(a: Any, b: Any) -> SubFOp: ...
def subi(a: Any, b: Any) -> SubIOp: ...

# ===== Dtype handles & module metadata =====

__ffi_default_bool_ty__: IntegerType
__ffi_default_float_ty__: FloatType
__ffi_default_int_ty__: IntegerType
__ffi_op_classes__: dict[Any, Any]
__ffi_parsers__: dict[Any, Any]
f16: FloatType
f32: FloatType
f64: FloatType
i1: IntegerType
i16: IntegerType
i32: IntegerType
i64: IntegerType
i8: IntegerType
index: IntegerType
