# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini._mlir_pkg.func
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini._mlir_pkg.func
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class CallOp(Object):
    callee: str
    args: List[Any]


class FuncOp(Object):
    name: str
    params: List[Value]
    body: List[Any]


class ReturnOp(Object):
    value: Any



# ===== Factories / hooks =====

def __getattr__(name: str, _cls: type = ..., _cf: str = ..., _af: str = ..., _prefix: str = ...) -> Any: ...
def call(callee: str, *args: Any) -> CallOp: ...
def func(parser: Any, node: Any) -> Any: ...
def ret(_parser: Any, value: Any) -> Any: ...

# ===== Dtype handles & module metadata =====

__ffi_parsers__: dict[Any, Any]
