# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini._mlir_pkg.memref
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini._mlir_pkg.memref
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class LoadOp(Object):
    ref: Value
    indices: List[Any]


class MemRefType(Object):
    shape: Any
    elem_type: Any


class StoreOp(Object):
    ref: Value
    value: Any
    indices: List[Any]



# ===== Factories / hooks =====

def __ffi_assign__(parser: Any, node: Any, _store: Optional[type] = ..., _bind: Optional[type] = ..., _this_module: 'ModuleType' = ...) -> Any: ...
def buffer_store(_parser: Any, target: Any, indices: list, value: Any) -> Any: ...
def load(_parser: Any, obj: Any, indices: list) -> Any: ...
def load_op(ref: Value, indices: List[Any]) -> LoadOp: ...
def memref(shape: Any, elem_type: Any) -> MemRefType: ...
def store_op(value: Any, ref: Value, indices: List[Any]) -> StoreOp: ...

# ===== Dtype handles & module metadata =====

__ffi_parsers__: dict[Any, Any]
