# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini._mlir_pkg.scf
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini._mlir_pkg.scf
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class ScfForOp(Object):
    iv: Value
    lb: Any
    ub: Any
    step: Any
    body: List[Any]


class ScfIfOp(Object):
    cond: Any
    then_body: List[Any]
    else_body: List[Any]



# ===== Factories / hooks =====

def __ffi_range_default__(*args: Any, step: Any = ..., annotations: Any = ...) -> 'pyast.ForFrame': ...
def if_stmt(_parser: Any, cond: Any, then_body: list, else_body: list) -> Any: ...
def range(*args: Any, step: Any = ..., annotations: Any = ...) -> 'pyast.ForFrame': ...

# ===== Dtype handles & module metadata =====

__ffi_default_bool_ty__: _DtypeHandle
__ffi_default_float_ty__: _DtypeHandle
__ffi_default_int_ty__: _DtypeHandle
__ffi_parsers__: dict[Any, Any]
bfloat16: _DtypeHandle
bool: _DtypeHandle
float16: _DtypeHandle
float32: _DtypeHandle
float4_e2m1fnx2: _DtypeHandle
float64: _DtypeHandle
float8_e4m3fn: _DtypeHandle
float8_e4m3fnuz: _DtypeHandle
float8_e5m2: _DtypeHandle
float8_e5m2fnuz: _DtypeHandle
float8_e8m0fnu: _DtypeHandle
int16: _DtypeHandle
int32: _DtypeHandle
int64: _DtypeHandle
int8: _DtypeHandle
uint16: _DtypeHandle
uint32: _DtypeHandle
uint64: _DtypeHandle
uint8: _DtypeHandle
