# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini._mlir_pkg.scf
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini._mlir_pkg.scf
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class ScfForOp(Object):
    iv: Value
    lb: Any
    ub: Any
    step: Any
    body: List[Any]


class ScfIfOp(Object):
    cond: Any
    then_body: List[Any]
    else_body: List[Any]



# ===== Factories / hooks =====

def for_stmt(parser: Any, node: Any, iter_val: Any) -> Any: ...
def if_stmt(_parser: Any, cond: Any, then_body: list, else_body: list) -> Any: ...
def range(*args: Any, step: Any = ...) -> _ScfRange: ...

# ===== Dtype handles & module metadata =====

__ffi_parsers__: dict[Any, Any]
