# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini.mlir
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini.mlir
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser

# ===== Dtype handles & module metadata =====

LANG_MODULES: dict[Any, Any]
