# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini.relax
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini.relax
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class Bind(Object):
    value: Any
    var: Var


class Call(Object):
    op_name: str
    args: List[Any]


class CallTIR(Object):
    args: List[Any]


class DataflowBlock(Object):
    body: List[Any]


class Function(Object):
    name: str
    params: List[Var]
    body: List[Any]


class IRModule(Object):
    name: str
    funcs: List[Any]


class ReturnOp(Object):
    value: Any


class TensorStructInfo(Object):
    shape: Any
    dtype: Any


class Var(Object):
    name: str
    ty: Any



# ===== Factories / hooks =====

def Tensor(shape: Any = ..., dtype: Any = ...) -> TensorStructInfo: ...
def __ffi_assign__(parser: Any, node: Any, _store: Optional[type] = ..., _bind: Optional[type] = ..., _this_module: 'ModuleType' = ...) -> Any: ...
def __ffi_make_var__(_parser: Any, name: str, ty: Any, _cls: type = ..., _nf: str = ..., _tf: str = ..., _pty: Optional[type] = ..., _pf: Optional[str] = ...) -> Any: ...
def __getattr__(name: str, _cls: type = ..., _cf: str = ..., _af: str = ..., _prefix: str = ...) -> Any: ...
def bind(_parser: Any, var: Any, rhs: Any) -> Any: ...
def call_tir(callee: Any, args: Any, out_sinfo: Any) -> CallTIR: ...
def dataflow(_mcls: type = ...) -> Any: ...
def function(parser: Any, node: Any) -> Any: ...
def ir_module(parser: Any, node: Any) -> Any: ...
def output(*values: Any) -> Call: ...
def ret(_parser: Any, value: Any) -> Any: ...

# ===== Dtype handles & module metadata =====

__ffi_parsers__: dict[Any, Any]
