# Auto-generated by ``tvm-ffi-stubgen dialects``. DO NOT EDIT.
#
# Source module: tvm_ffi.testing.mini.tir
# Regenerate with:
#     tvm-ffi-stubgen dialects tvm_ffi.testing.mini.tir
#
# This stub declares every dialect attribute that
# :func:`tvm_ffi.dialect_autogen.finalize_module` injects (dtype
# handles, factory / decorator handlers, parser hooks, ``__ffi_*``
# metadata, parse hooks). IR-class bodies mirror the ``.py`` source
# for ``@py_class`` classes so IDEs and type-checkers keep seeing
# their fields.

from __future__ import annotations

from types import ModuleType
from typing import Any, Callable, Dict, List, Mapping, MutableMapping, Optional, Sequence, Set, Tuple, Union

from tvm_ffi import Object
from tvm_ffi.pyast import Frame, FuncFrame, IRParser


# ===== IR classes =====

class Add(Object):
    lhs: Any
    rhs: Any


class And(Object):
    lhs: Any
    rhs: Any


class AssertStmt(Object):
    cond: Any
    message: Optional[str]


class Bind(Object):
    value: Any
    var: Var


class Block(Object):
    body: List[Any]


class BufferLoad(Object):
    source: Var
    indices: List[Any]


class BufferStore(Object):
    buffer: Var
    value: Any
    indices: List[Any]


class BufferTy(Object):
    shape: Any
    dtype: str
    strides: Optional[List[int]]
    offset: Optional[int]
    scope: Optional[str]


class Call(Object):
    op_name: str
    args: List[Any]


class Cast(Object):
    target: PrimTy
    value: Any


class Eq(Object):
    lhs: Any
    rhs: Any


class Evaluate(Object):
    value: Any


class Flag(Object):
    kind: str
    count: int


class FlagV2(Object):
    kind: str


class FloatImm(Object):
    value: float
    dtype: Any


class For(Object):
    loop_var: Var
    start: Any
    end: Any
    step: Any
    body: List[Any]
    kind: str
    annotations: Optional[Any]


class IfThenElse(Object):
    cond: Any
    then_body: List[Any]
    else_body: List[Any]


class IntImm(Object):
    value: int
    dtype: Any


class Lt(Object):
    lhs: Any
    rhs: Any


class Mul(Object):
    lhs: Any
    rhs: Any


class Not(Object):
    a: Any


class Or(Object):
    lhs: Any
    rhs: Any


class PrimFunc(Object):
    name: str
    params: List[Var]
    body: List[Any]
    attrs: Optional[dict]


class PrimTy(Object):
    dtype: str


class SeqStmt(Object):
    stmts: List[Any]


class Sub(Object):
    lhs: Any
    rhs: Any


class Var(Object):
    name: str
    ty: PrimTy


class While(Object):
    cond: Any
    body: List[Any]


class __ffi_prim_ty__(Object):
    dtype: str



# ===== Factories / hooks =====

def Buffer(shape: Any, dtype: str, strides: Optional[Sequence[int]] = ..., elem_offset: Optional[int] = ..., scope: Optional[str] = ...) -> BufferTy: ...
def __ffi_assign__(parser: Any, node: Any, _store: Optional[type] = ..., _bind: Optional[type] = ..., _this_module: 'ModuleType' = ...) -> Any: ...
def __ffi_make_var__(_parser: Any, name: str, ty: Any, _cls: type = ..., _nf: str = ..., _tf: str = ..., _pty: Optional[type] = ..., _pf: Optional[str] = ...) -> Any: ...
def __getattr__(name: str, _cls: type = ..., _cf: str = ..., _af: str = ..., _prefix: str = ...) -> Any: ...
def assert_stmt(_parser: Any, cond: Any, msg: Any) -> Any: ...
def bind(_parser: Any, var: Any, rhs: Any) -> Any: ...
def block(_mcls: type = ...) -> Any: ...
def buffer_store(_parser: Any, target: Any, indices: list, value: Any) -> Any: ...
def evaluate(value: Any) -> Evaluate: ...
def for_stmt(parser: Any, node: Any, iter_val: Any) -> Any: ...
def func_attr(parser: 'IRParser', *args: Any, **kwargs: Any) -> None: ...
def if_stmt(_parser: Any, cond: Any, then_body: list, else_body: list) -> Any: ...
def imm(value: Union[int, float], dtype: Any) -> Any: ...
def load(_parser: Any, obj: Any, indices: list) -> Any: ...
def make_var_factory(name: str, ty: Any) -> Var: ...
def parallel(*args: Any, step: Any = ..., annotations: Any = ...) -> Any: ...
def prim_func(parser: Any, node: Any) -> Any: ...
def ret(_parser: Any, value: Any) -> Evaluate: ...
def serial(*args: Any, step: Any = ..., annotations: Any = ...) -> Any: ...
def unroll(*args: Any, step: Any = ..., annotations: Any = ...) -> Any: ...
def vectorized(*args: Any, step: Any = ..., annotations: Any = ...) -> Any: ...
def while_stmt(_parser: Any, cond: Any, body: list) -> Any: ...

# ===== Dtype handles & module metadata =====

LANG_MODULES: dict[Any, Any]
T: Any  # module alias
TLang: Any  # module alias
__ffi_default_bool_ty__: _DtypeHandle
__ffi_default_float_ty__: _DtypeHandle
__ffi_default_int_ty__: _DtypeHandle
__ffi_op_classes__: dict[Any, Any]
__ffi_parsers__: dict[Any, Any]
bool: _DtypeHandle
float16: _DtypeHandle
float32: _DtypeHandle
float64: _DtypeHandle
int16: _DtypeHandle
int32: _DtypeHandle
int64: _DtypeHandle
int8: _DtypeHandle
uint16: _DtypeHandle
uint32: _DtypeHandle
uint64: _DtypeHandle
uint8: _DtypeHandle
